In [ ]:
from pymongo import MongoClient
import random
import numpy as np
import secrets
import string

In [ ]:
client = MongoClient("mongodb://localhost:27017/")

db = client["college"]

students_collection = db["students"]
subjects_collection = db["subjects"]
classes_collection = db["classes"]
faculty_collection = db["faculty"]

In [ ]:
subjects = [
    {"subject_id": "CSE101", "name": "Introduction to Python", "type": "absolute", "credits": 3},
    {"subject_id": "CSE102", "name": "Engineering Chemistry", "type": "relative", "credits": 3},
    {"subject_id": "CSE103", "name": "Engineering Calculus", "type": "relative", "credits": 4},
    {"subject_id": "CSE104", "name": "Introduction to C++", "type": "absolute", "credits": 3},
    {"subject_id": "CSE105", "name": "Differential Equations and Transforms", "type": "relative", "credits": 3},
    {"subject_id": "CSE106", "name": "Data Structures and Algorithms", "type": "relative", "credits": 4},
    {"subject_id": "CSE107", "name": "Introduction to Java", "type": "absolute", "credits": 3},
    {"subject_id": "CSE108", "name": "Discrete Mathematics and Graph Theory", "type": "relative", "credits": 3},
    {"subject_id": "CSE109", "name": "Complex Variables and Linear Algebra", "type": "relative", "credits": 4},
    {"subject_id": "CSE110", "name": "Web Programming", "type": "absolute", "credits": 3},
    {"subject_id": "CSE111", "name": "Design and Analysis of Algorithms", "type": "relative", "credits": 3},
    {"subject_id": "CSE112", "name": "Theory of Computation", "type": "relative", "credits": 4},
    {"subject_id": "CSE113", "name": "Backend Applications", "type": "absolute", "credits": 3},
    {"subject_id": "CSE114", "name": "Microcontrollers and Microprocessors", "type": "relative", "credits": 3},
    {"subject_id": "CSE115", "name": "Computer Architecture and Organisation", "type": "relative", "credits": 4},
    {"subject_id": "CSE116", "name": "Database Applications", "type": "absolute", "credits": 3},
    {"subject_id": "CSE117", "name": "Database Management Systems", "type": "relative", "credits": 3},
    {"subject_id": "CSE118", "name": "Compiler Design", "type": "relative", "credits": 4}
]

subjects_collection.insert_many(subjects)

In [ ]:
students = [
    {
        "name": "Rohit Singh",
        "register_number": "21BCE0001",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE104', 'CSE105', 'CSE106', 'CSE107']},
            {"semester_name": "F2223", "subject_list": ['CSE108', 'CSE109', 'CSE110', 'CSE113']},
            {"semester_name": "W2223", "subject_list": ['CSE111', 'CSE112', 'CSE114']},
            {"semester_name": "F2324", "subject_list": ['CSE115', 'CSE116', 'CSE117', 'CSE118']},
            {"semester_name": "W2324", "subject_list": []}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Priya Sharma",
        "register_number": "21BCE0002",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE104', 'CSE105']},
            {"semester_name": "F2223", "subject_list": ['CSE106', 'CSE107', 'CSE108', 'CSE109']},
            {"semester_name": "W2223", "subject_list": ['CSE110', 'CSE111', 'CSE112']},
            {"semester_name": "F2324", "subject_list": ['CSE113', 'CSE114']},
            {"semester_name": "W2324", "subject_list": ['CSE115', 'CSE116', 'CSE117', 'CSE118']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Vikram Joshi",
        "register_number": "21BCE0003",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE104', 'CSE105', 'CSE106', 'CSE107']},
            {"semester_name": "F2223", "subject_list": ['CSE107', 'CSE108', 'CSE109', 'CSE110']},
            {"semester_name": "W2223", "subject_list": ['CSE111', 'CSE112']},
            {"semester_name": "F2324", "subject_list": ['CSE113', 'CSE114', 'CSE115', 'CSE116']},
            {"semester_name": "W2324", "subject_list": ['CSE117', 'CSE118']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Meera Kumar",
        "register_number": "21BCE0004",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE104', 'CSE106']},
            {"semester_name": "F2223", "subject_list": ['CSE105', 'CSE108']},
            {"semester_name": "W2223", "subject_list": ['CSE107', 'CSE110', 'CSE111']},
            {"semester_name": "F2324", "subject_list": ['CSE109', 'CSE112', 'CSE113', 'CSE114']},
            {"semester_name": "W2324", "subject_list": ['CSE115', 'CSE116', 'CSE117', 'CSE118']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Amit Gupta",
        "register_number": "21BCE0005",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE104', 'CSE105', 'CSE106', 'CSE107']},
            {"semester_name": "F2223", "subject_list": ['CSE108', 'CSE109', 'CSE110', 'CSE111']},
            {"semester_name": "W2223", "subject_list": ['CSE112', 'CSE113', 'CSE114', 'CSE115']},
            {"semester_name": "F2324", "subject_list": ['CSE116', 'CSE117', 'CSE118']},
            {"semester_name": "W2324", "subject_list": []}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Neha Iyer",
        "register_number": "21BCE0006",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE105', 'CSE106']},
            {"semester_name": "F2223", "subject_list": ['CSE107', 'CSE108', 'CSE109']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE110', 'CSE111', 'CSE112']},
            {"semester_name": "F2324", "subject_list": ['CSE113', 'CSE114', 'CSE115']},
            {"semester_name": "W2324", "subject_list": ['CSE116', 'CSE117', 'CSE118']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Rajesh Patel",
        "register_number": "21BCE0007",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2223", "subject_list": ['CSE107']},
            {"semester_name": "W2223", "subject_list": ['CSE110', 'CSE111', 'CSE112']},
            {"semester_name": "F2324", "subject_list": ['CSE108', 'CSE113', 'CSE114', 'CSE109']},
            {"semester_name": "W2324", "subject_list": ['CSE115', 'CSE116', 'CSE117', 'CSE118']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Kavya Rawat",
        "register_number": "21BCE0008",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2223", "subject_list": ['CSE107', 'CSE108', 'CSE109']},
            {"semester_name": "W2223", "subject_list": ['CSE110', 'CSE111', 'CSE112']},
            {"semester_name": "F2324", "subject_list": ['CSE113', 'CSE114', 'CSE115']},
            {"semester_name": "W2324", "subject_list": ['CSE112', 'CSE116', 'CSE117', 'CSE118']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Arun Desai",
        "register_number": "21BCE0009",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2223", "subject_list": ['CSE107', 'CSE108', 'CSE109']},
            {"semester_name": "W2223", "subject_list": ['CSE110', 'CSE111', 'CSE112']},
            {"semester_name": "F2324", "subject_list": ['CSE113', 'CSE114', 'CSE116', 'CSE117']},
            {"semester_name": "W2324", "subject_list": ['CSE115', 'CSE118']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Pooja Mehta",
        "register_number": "21BCE0010",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE102', 'CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2223", "subject_list": ['CSE107', 'CSE108', 'CSE109']},
            {"semester_name": "W2223", "subject_list": ['CSE110', 'CSE111', 'CSE112']},
            {"semester_name": "F2324", "subject_list": ['CSE113', 'CSE114']},
            {"semester_name": "W2324", "subject_list": ['CSE115', 'CSE116', 'CSE117', 'CSE118']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Sanjay Verma",
        "register_number": "21BCE0011",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE105', 'CSE106']},
            {"semester_name": "F2223", "subject_list": ['CSE107', 'CSE108', 'CSE109', 'CSE104']},
            {"semester_name": "W2223", "subject_list": ['CSE110', 'CSE111', 'CSE112']},
            {"semester_name": "F2324", "subject_list": ['CSE113', 'CSE114', 'CSE115', 'CSE116']},
            {"semester_name": "W2324", "subject_list": ['CSE113', 'CSE117', 'CSE118']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Sakshi Pandey",
        "register_number": "21BCE0012",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE104', 'CSE105']},
            {"semester_name": "F2223", "subject_list": ['CSE106', 'CSE107', 'CSE108', 'CSE109']},
            {"semester_name": "W2223", "subject_list": ['CSE110', 'CSE111', 'CSE112', 'CSE113']},
            {"semester_name": "F2324", "subject_list": ['CSE114', 'CSE115']},
            {"semester_name": "W2324", "subject_list": ['CSE116', 'CSE117', 'CSE118']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Karan Khanna",
        "register_number": "21BCE0013",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2223", "subject_list": ['CSE107', 'CSE108', 'CSE109', 'CSE110']},
            {"semester_name": "W2223", "subject_list": ['CSE111', 'CSE112']},
            {"semester_name": "F2324", "subject_list": ['CSE113', 'CSE114']},
            {"semester_name": "W2324", "subject_list": ['CSE115', 'CSE116', 'CSE117', 'CSE118']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Vivek Patel",
        "register_number": "21BCE0014",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2223", "subject_list": ['CSE107', 'CSE108', 'CSE109']},
            {"semester_name": "W2223", "subject_list": ['CSE110', 'CSE111', 'CSE112']},
            {"semester_name": "F2324", "subject_list": ['CSE113', 'CSE114']},
            {"semester_name": "W2324", "subject_list": ['CSE115', 'CSE116', 'CSE117', 'CSE118']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Aditya Kapoor",
        "register_number": "21BCE0015",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2223", "subject_list": ['CSE107', 'CSE108', 'CSE109']},
            {"semester_name": "W2223", "subject_list": ['CSE110', 'CSE111', 'CSE112', 'CSE113']},
            {"semester_name": "F2324", "subject_list": ['CSE114', 'CSE115', 'CSE118']},
            {"semester_name": "W2324", "subject_list": ['CSE116', 'CSE117']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Nikhil Reddy",
        "register_number": "21BCE0016",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2223", "subject_list": ['CSE107', 'CSE108']},
            {"semester_name": "W2223", "subject_list": ['CSE109', 'CSE110', 'CSE111']},
            {"semester_name": "F2324", "subject_list": ['CSE113', 'CSE114', 'CSE115']},
            {"semester_name": "W2324", "subject_list": ['CSE112', 'CSE116', 'CSE117', 'CSE118']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Ananya Singh",
        "register_number": "21BCE0017",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2223", "subject_list": ['CSE107', 'CSE108', 'CSE109']},
            {"semester_name": "W2223", "subject_list": ['CSE110', 'CSE111', 'CSE112']},
            {"semester_name": "F2324", "subject_list": ['CSE113', 'CSE114', 'CSE115']},
            {"semester_name": "W2324", "subject_list": ['CSE116', 'CSE117', 'CSE118']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Siddharth Patel",
        "register_number": "21BCE0018",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2223", "subject_list": ['CSE107', 'CSE108', 'CSE109', 'CSE110']},
            {"semester_name": "W2223", "subject_list": ['CSE111', 'CSE112']},
            {"semester_name": "F2324", "subject_list": ['CSE113', 'CSE114', 'CSE115', 'CSE116']},
            {"semester_name": "W2324", "subject_list": ['CSE117', 'CSE118']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Ishaan Kumar",
        "register_number": "21BCE0019",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE104', 'CSE105', 'CSE106', 'CSE107']},
            {"semester_name": "F2223", "subject_list": ['CSE105', 'CSE108', 'CSE109']},
            {"semester_name": "W2223", "subject_list": ['CSE110', 'CSE111', 'CSE112']},
            {"semester_name": "F2324", "subject_list": ['CSE113', 'CSE114', 'CSE115']},
            {"semester_name": "W2324", "subject_list": ['CSE113', 'CSE115', 'CSE116', 'CSE117']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Aditi Kumari",
        "register_number": "21BCE0020",
        "semester_data": [
            {"semester_name": "F2122", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2122", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2223", "subject_list": ['CSE107', 'CSE108', 'CSE109', 'CSE110']},
            {"semester_name": "W2223", "subject_list": ['CSE111', 'CSE112', 'CSE113', 'CSE114']},
            {"semester_name": "F2324", "subject_list": ['CSE115', 'CSE116']},
            {"semester_name": "W2324", "subject_list": ['CSE117', 'CSE118']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Aaravya Sharma",
        "register_number": "22BCE0001",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105']},
            {"semester_name": "F2324", "subject_list": ['CSE106', 'CSE107', 'CSE108']},
            {"semester_name": "W2324", "subject_list": ['CSE109', 'CSE110', 'CSE111', 'CSE104']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Aditiya Mehta",
        "register_number": "22BCE0002",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE106', 'CSE107']},
            {"semester_name": "F2324", "subject_list": ['CSE108', 'CSE109', 'CSE110']},
            {"semester_name": "W2324", "subject_list": ['CSE111', 'CSE112', 'CSE104']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Arjun Aggarwala",
        "register_number": "22BCE0003",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105']},
            {"semester_name": "F2324", "subject_list": ['CSE106', 'CSE107', 'CSE108']},
            {"semester_name": "W2324", "subject_list": ['CSE109', 'CSE110', 'CSE111', 'CSE105']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Ruchika Rao",
        "register_number": "22BCE0004",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2324", "subject_list": ['CSE107', 'CSE108', 'CSE109']},
            {"semester_name": "W2324", "subject_list": ['CSE110', 'CSE111', 'CSE112']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Sneha Gupta",
        "register_number": "22BCE0005",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105']},
            {"semester_name": "F2324", "subject_list": ['CSE106', 'CSE107', 'CSE108']},
            {"semester_name": "W2324", "subject_list": ['CSE109', 'CSE110', 'CSE105']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Mohan Desai",
        "register_number": "22BCE0006",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105']},
            {"semester_name": "F2324", "subject_list": ['CSE106', 'CSE107', 'CSE108']},
            {"semester_name": "W2324", "subject_list": ['CSE109', 'CSE110']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Ananya Pandey",
        "register_number": "22BCE0007",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105']},
            {"semester_name": "F2324", "subject_list": ['CSE106', 'CSE107', 'CSE108']},
            {"semester_name": "W2324", "subject_list": ['CSE109', 'CSE110', 'CSE111', 'CSE112']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Rajiv Singh",
        "register_number": "22BCE0008",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2324", "subject_list": ['CSE107', 'CSE108', 'CSE109']},
            {"semester_name": "W2324", "subject_list": ['CSE110', 'CSE111']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Suriya Nair",
        "register_number": "22BCE0009",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2324", "subject_list": ['CSE107', 'CSE108']},
            {"semester_name": "W2324", "subject_list": ['CSE109', 'CSE110', 'CSE111', 'CSE112']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Avik Chatterjee",
        "register_number": "22BCE0010",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105']},
            {"semester_name": "F2324", "subject_list": ['CSE106', 'CSE107', 'CSE108']},
            {"semester_name": "W2324", "subject_list": ['CSE109', 'CSE110']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Ritika Singh",
        "register_number": "22BCE0011",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105']},
            {"semester_name": "F2324", "subject_list": ['CSE106', 'CSE107', 'CSE108']},
            {"semester_name": "W2324", "subject_list": ['CSE109', 'CSE110', 'CSE105']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Poojha Nair",
        "register_number": "22BCE0012",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105']},
            {"semester_name": "F2324", "subject_list": ['CSE106', 'CSE107', 'CSE108']},
            {"semester_name": "W2324", "subject_list": ['CSE109', 'CSE110']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Amit Patel",
        "register_number": "22BCE0013",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2324", "subject_list": ['CSE107', 'CSE108', 'CSE109']},
            {"semester_name": "W2324", "subject_list": ['CSE110', 'CSE111', 'CSE112']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Deepak Mehta",
        "register_number": "22BCE0014",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105']},
            {"semester_name": "F2324", "subject_list": ['CSE106', 'CSE107', 'CSE108']},
            {"semester_name": "W2324", "subject_list": ['CSE109', 'CSE110', 'CSE111']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Ishita Singh",
        "register_number": "22BCE0015",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2324", "subject_list": ['CSE107', 'CSE108', 'CSE109']},
            {"semester_name": "W2324", "subject_list": ['CSE110', 'CSE111', 'CSE112']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Karan Sharma",
        "register_number": "22BCE0016",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2324", "subject_list": ['CSE107', 'CSE108', 'CSE109']},
            {"semester_name": "W2324", "subject_list": ['CSE108', 'CSE110', 'CSE111']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Lakshmi Reddy",
        "register_number": "22BCE0017",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105']},
            {"semester_name": "F2324", "subject_list": ['CSE106', 'CSE107', 'CSE108']},
            {"semester_name": "W2324", "subject_list": ['CSE109', 'CSE110', 'CSE111', 'CSE112']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Meera Iyer",
        "register_number": "22BCE0018",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2324", "subject_list": ['CSE107', 'CSE108', 'CSE109']},
            {"semester_name": "W2324", "subject_list": ['CSE110', 'CSE111']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Nitin Khanna",
        "register_number": "22BCE0019",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105']},
            {"semester_name": "F2324", "subject_list": ['CSE106', 'CSE107', 'CSE108']},
            {"semester_name": "W2324", "subject_list": ['CSE109', 'CSE110', 'CSE111']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Varun Chopra",
        "register_number": "22BCE0020",
        "semester_data": [
            {"semester_name": "F2223", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2223", "subject_list": ['CSE104', 'CSE105', 'CSE106']},
            {"semester_name": "F2324", "subject_list": ['CSE107', 'CSE108', 'CSE109']},
            {"semester_name": "W2324", "subject_list": ['CSE110', 'CSE111', 'CSE112']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Aarav Sharma",
        "register_number": "23BCE0001",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE104', 'CSE105CSE106']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Aditi Mehta",
        "register_number": "23BCE0002",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE104', 'CSE105']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Arjun Patel",
        "register_number": "23BCE0003",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE104', 'CSE105', 'CSE106']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Anika Verma",
        "register_number": "23BCE0004",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE105', 'CSE106']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Anushka Joshi",
        "register_number": "23BCE0005",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE104', 'CSE105', 'CSE106', 'CSE107']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Nikhil Iyer",
        "register_number": "23BCE0006",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE105', 'CSE106', 'CSE107']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Sneha Gupta",
        "register_number": "23BCE0007",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE104', 'CSE106']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Siddharth Nair",
        "register_number": "23BCE0008",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE104', 'CSE105']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Tara Sharma",
        "register_number": "23BCE0009",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE104', 'CSE105', 'CSE106']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Varun Desai",
        "register_number": "23BCE0010",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE105', 'CSE106', 'CSE107']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Riya Sharma",
        "register_number": "23BCE0011",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE104', 'CSE105']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Arjun Mehta",
        "register_number": "23BCE0012",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE104', 'CSE106', 'CSE107']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Priya Patel",
        "register_number": "23BCE0013",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE104', 'CSE105']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Kavya Rao",
        "register_number": "23BCE0014",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE104', 'CSE106', 'CSE107']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Neha Gupta",
        "register_number": "23BCE0015",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE104', 'CSE106', 'CSE107']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Rohan Desai",
        "register_number": "23BCE0016",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE104', 'CSE105']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Ananya Iyer",
        "register_number": "23BCE0017",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE105', 'CSE106']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Rajiv Singh",
        "register_number": "23BCE0018",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE104', 'CSE105', 'CSE106']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Priya Nair",
        "register_number": "23BCE0019",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE104', 'CSE105', 'CSE106']}
        ],
        "completed": [],
        "arrear": []
    },
    {
        "name": "Suresh Joshi",
        "register_number": "23BCE0020",
        "semester_data": [
            {"semester_name": "F2324", "subject_list": ['CSE101', 'CSE102', 'CSE103']},
            {"semester_name": "W2324", "subject_list": ['CSE105', 'CSE106']}
        ],
        "completed": [],
        "arrear": []
    }
    ]
students_collection.insert_many(students)

In [ ]:
# Arrays for subject lists

sem_arr = ["F2122", "W2122", "F2223", "W2223", "F2324", "W2324"]

subjects = list(subjects_collection.find({}, {"_id": 0, "subject_id": 1, "type": 1}))

sub_arr = [subject["subject_id"] for subject in subjects]

In [ ]:
def generate_relative_marks(num_students):
    marks = []
    for _ in range(num_students):
        student_marks = {
            "cat1": min(max(int(random.gauss(32, 15)), 0), 50),
            "cat2": min(max(int(random.gauss(32, 15)), 0), 50),
            "quiz1": min(max(int(random.gauss(6.5, 3)), 0), 10),
            "quiz2": min(max(int(random.gauss(6.5, 3)), 0), 10),
            "da": min(max(int(random.gauss(9, 1)), 0), 10),
            "fat": min(max(int(random.gauss(65, 25)), 0), 100),
            "total_marks": 0,
            "grade": 0
        }
        marks.append(student_marks)
    return marks

def generate_absolute_marks(num_students):
    marks = []
    for _ in range(num_students):
        student_marks = {
            "ia1": min(max(int(random.gauss(17, 3)), 0), 20),
            "mt": min(max(int(random.gauss(17, 3)), 0), 20),
            "ia2": min(max(int(random.gauss(17, 3)), 0), 20),
            "fat": min(max(int(random.gauss(32, 5)), 0), 40),
            "total_marks": 0,
            "grade": 0
        }
        marks.append(student_marks)
    return marks

In [ ]:
def fetch_student_data(semester_name, subject):
    query = {
        "semester_data": {
            "$elemMatch": {
            "semester_name": semester_name,
            "subject_list": subject
            }
        }
    }
    projection = {"register_number": 1, "_id": 0}
    results = students_collection.find(query, projection)
    register_numbers = [student["register_number"] for student in results]
    return register_numbers

In [ ]:
def format_class_data(class_number, subject_id, student_data, marks_data, subject_type):
    class_data = {
        "class_number": class_number,
        "subject_id": subject_id,
        "faculty_id": "",  
        "student_data": [],
    }
    for i, student in enumerate(student_data):
        student_marks = marks_data[i]
        student_entry = {"register_number": student}
        if subject_type == "relative":
            student_entry.update({
                "cat1": student_marks["cat1"],
                "cat2": student_marks["cat2"],
                "quiz1": student_marks["quiz1"],
                "quiz2": student_marks["quiz2"],
                "da": student_marks["da"],
                "fat": student_marks["fat"],
                "total_marks": student_marks["total_marks"],
                "grade": student_marks["grade"]
            })
        else:
            student_entry.update({
                "ia1": student_marks["ia1"],
                "mt": student_marks["mt"],
                "ia2": student_marks["ia2"],
                "fat": student_marks["fat"],
                "total_marks": student_marks["total_marks"],
                "grade": student_marks["grade"]
            })
        class_data["student_data"].append(student_entry)
    return class_data

In [ ]:
# Distributing students into classes

class_number_counter = {sem: 1 for sem in sem_arr} # To track current class number for each semester

for sem in sem_arr:
    for sub in sub_arr:
        subject = subjects_collection.find_one({"subject_id": sub}, {"_id": 0, "type": 1})
        subject_type = subject["type"]

        register_numbers = fetch_student_data(sem, sub)
        
        if subject_type == "relative":
            marks_data = generate_relative_marks(len(register_numbers))
        else:
            marks_data = generate_absolute_marks(len(register_numbers))
        
        num_students = len(register_numbers)
        num_classes = (num_students // 10) + (1 if num_students % 10 != 0 else 0)
        
        start_index = 0
        for i in range(num_classes):
            end_index = min(start_index + 10, len(register_numbers))
            class_number = f"{sem}{'{:03d}'.format(class_number_counter[sem])}"
            student_data = register_numbers[start_index:end_index]
            formatted_class_data = format_class_data(class_number, sub, student_data, marks_data[start_index:end_index], subject_type)
            
            # Insert formatted class data into the classes collection
            classes_collection.insert_one(formatted_class_data)
            
            start_index = end_index
            class_number_counter[sem] += 1

print("Data has been successfully inserted into the classes collection.")

In [ ]:
faculty = [
    {
        "faculty_id": "00001", 
        "faculty_name": "Venkatesh Srinivasan", 
        "class_data": [
            {"semester_name": "F2122", "class_list": []},
            {"semester_name": "W2122", "class_list": []},
            {"semester_name": "F2223", "class_list": []},
            {"semester_name": "W2223", "class_list": []},
            {"semester_name": "F2324", "class_list": []},
            {"semester_name": "W2324", "class_list": []}        
        ]
    },
    {
        "faculty_id": "00002", 
        "faculty_name": "Lakshmana Raghavachari", 
        "class_data": [
            {"semester_name": "F2122", "class_list": []},
            {"semester_name": "W2122", "class_list": []},
            {"semester_name": "F2223", "class_list": []},
            {"semester_name": "W2223", "class_list": []},
            {"semester_name": "F2324", "class_list": []},
            {"semester_name": "W2324", "class_list": []}        
        ]
    },
    {
        "faculty_id": "00003", 
        "faculty_name": "Parameshwara Subramanian", 
        "class_data": [
            {"semester_name": "F2122", "class_list": []},
            {"semester_name": "W2122", "class_list": []},
            {"semester_name": "F2223", "class_list": []},
            {"semester_name": "W2223", "class_list": []},
            {"semester_name": "F2324", "class_list": []},
            {"semester_name": "W2324", "class_list": []}        
        ]
    },
    {
        "faculty_id": "00004", 
        "faculty_name": "Padmanabhan Krishnamurthy", 
        "class_data": [
            {"semester_name": "F2122", "class_list": []},
            {"semester_name": "W2122", "class_list": []},
            {"semester_name": "F2223", "class_list": []},
            {"semester_name": "W2223", "class_list": []},
            {"semester_name": "F2324", "class_list": []},
            {"semester_name": "W2324", "class_list": []}        
        ]
    },
    {
        "faculty_id": "00005", 
        "faculty_name": "Rajagopalan Narayanaswamy", 
        "class_data": [
            {"semester_name": "F2122", "class_list": []},
            {"semester_name": "W2122", "class_list": []},
            {"semester_name": "F2223", "class_list": []},
            {"semester_name": "W2223", "class_list": []},
            {"semester_name": "F2324", "class_list": []},
            {"semester_name": "W2324", "class_list": []}        
        ]
    }
]

faculty_collection.insert_many(faculty)

In [ ]:
# Distribute classes to faculty

faculties = list(faculty_collection.find({}))

class_count_by_sem = {}
for sem in sem_arr:
    count = classes_collection.count_documents({ "class_number": { "$regex": f"^{sem}" } })
    class_count_by_sem[sem] = count

for sem in sem_arr:
    classes = list(classes_collection.find({ "class_number": { "$regex": f"^{sem}" } }))
    faculty_count = len(faculties)
    
    for i, class_data in enumerate(classes):
        faculty_index = i % faculty_count
        faculty = faculties[faculty_index]
        
        for entry in faculty["class_data"]:
            if entry["semester_name"] == sem:
                entry["class_list"].append(class_data["class_number"])
                break
        
        faculty_collection.update_one(
            { "faculty_id": faculty["faculty_id"] },
            { "$set": { "class_data": faculty["class_data"] } }
        )

print("Classes have been allocated to faculty.")

In [ ]:
def calculate_relative_total_marks(student):
    return (
        0.30 * student["cat1"] +
        0.30 * student["cat2"] +
        student["quiz1"] +
        student["quiz2"] +
        student["da"] +
        0.40 * student["fat"]
    )

def calculate_absolute_total_marks(student):
    return student["ia1"] + student["mt"] + student["ia2"] + student["fat"]

In [ ]:
# Update total_marks for each student in every class

classes = classes_collection.find()

for class_doc in classes:
    subject_id = class_doc["subject_id"]
    subject = subjects_collection.find_one({"subject_id": subject_id})
    
    if subject:
        subject_type = subject["type"]
        
        for student in class_doc["student_data"]:
            if subject_type == "relative":
                student["total_marks"] = calculate_relative_total_marks(student)
            else:
                student["total_marks"] = calculate_absolute_total_marks(student)
        
        classes_collection.update_one(
            {"_id": class_doc["_id"]},
            {"$set": {"student_data": class_doc["student_data"]}}
        )

print("Total marks have been calculated and updated.")

In [ ]:
def calculate_grade_points(total_marks, mean, sd):
    if total_marks >= mean + 1.5 * sd:
        return 10
    elif (mean + 0.5 * sd) <= total_marks < (mean + 1.5 * sd):
        return 9
    elif (mean - 0.5 * sd) <= total_marks < (mean + 0.5 * sd):
        return 8
    elif (mean - 1.0 * sd) <= total_marks < (mean - 0.5 * sd):
        return 7
    elif (mean - 1.5 * sd) <= total_marks < (mean - 1.0 * sd):
        return 6
    elif (mean - 2.0 * sd) <= total_marks < (mean - 1.5 * sd):
        return 5
    elif total_marks <= mean - 2 * sd:
        return 0
    else:
        return 0

In [ ]:
# Calculate grade points for each student

classes = classes_collection.find()

for class_doc in classes:
    student_data = class_doc['student_data']
    
    total_marks_list = [student['total_marks'] for student in student_data]
    
    mean_marks = np.mean(total_marks_list)
    sd_marks = np.std(total_marks_list)
    
    for student in student_data:
        total_marks = student['total_marks']
        grade_points = calculate_grade_points(total_marks, mean_marks, sd_marks)
        student['grade'] = grade_points
    
    classes_collection.update_one(
        {'_id': class_doc['_id']},
        {'$set': {'student_data': student_data}}
    )

print("Updated Grade points for all students in all classes.")

In [ ]:
students = students_collection.find()

for student in students:
    semester_data = student['semester_data']
    
    for semester in semester_data:
        subject_list = semester['subject_list']
        total_credits = 0
        total_weighted_points = 0
        
        for subject_id in subject_list:
            subject = subjects_collection.find_one({"subject_id": subject_id}) # Finding the subject to get the number of credits
            if not subject:
                continue
            credits = subject['credits']
            
            # Finding in class collection to get the student's GPA for a subject
            class_doc = classes_collection.find_one({"subject_id": subject_id, "student_data.register_number": student['register_number']})
            if not class_doc:
                continue
            student_data = next((s for s in class_doc['student_data'] if s['register_number'] == student['register_number']), None)
            if not student_data:
                continue
            grade = student_data['grade']
            
            total_weighted_points += grade * credits
            total_credits += credits
        
        if total_credits > 0:
            semester_gpa = total_weighted_points / total_credits
        else:
            semester_gpa = 0
        
        semester['gpa'] = semester_gpa
    
    students_collection.update_one(
        {'_id': student['_id']},
        {'$set': {'semester_data': semester_data}}
    )

print("Updated GPA for all semesters of all students.")

In [ ]:
students = students_collection.find()

for student in students:
    semester_data = student['semester_data']
    total_weighted_gpa = 0
    total_credits = 0
    
    for semester in semester_data:
        subject_list = semester['subject_list']
        semester_gpa = semester.get('gpa', 0)
        semester_credits = 0
        
        for subject_id in subject_list:
            subject = subjects_collection.find_one({"subject_id": subject_id})
            if not subject:
                continue
            credits = subject['credits']
            semester_credits += credits
        
        total_weighted_gpa += semester_gpa * semester_credits
        total_credits += semester_credits
    
    if total_credits > 0:
        cgpa = total_weighted_gpa / total_credits
    else:
        cgpa = 0
    
    students_collection.update_one(
        {'_id': student['_id']},
        {'$set': {'cgpa': cgpa}}
    )

print("Updated CGPA for all students.")

In [ ]:
def generate_password(length=12):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(secrets.choice(characters) for _ in range(length))
    return password

students_collection = db['students']
students = students_collection.find()
for student in students:
    password = generate_password()
    students_collection.update_one(
        {'_id': student['_id']},
        {'$set': {'password': password}}
    )

faculty_collection = db['faculty']
faculty = faculty_collection.find()
for member in faculty:
    password = generate_password()
    faculty_collection.update_one(
        {'_id': member['_id']},
        {'$set': {'password': password}}
    )

print("Passwords generated and updated for students and faculty.")

In [ ]:
faculties = db.faculty.find()

for faculty in faculties:
    faculty_id = faculty["faculty_id"]
    for class_entry in faculty["class_data"]:
        class_list = class_entry["class_list"]
        for class_number in class_list:
            db.classes.update_one({"class_number": class_number}, {"$set": {"faculty_id": faculty_id}})

print("Allocated faculty_ids to all classes")

In [ ]:
students = db.students.find()

for student in students:
    register_number = student['register_number']
    completed = set(student.get('completed', []))
    arrear = set(student.get('arrear', []))

    for semester_data in student.get('semester_data', []):
        subject_list = semester_data.get('subject_list', [])
        
        for subject_id in subject_list:
            class_document = db.classes.find_one({
                "subject_id": subject_id,
                "student_data.register_number": register_number
            })

            if class_document:
                student_data = next((data for data in class_document['student_data'] if data['register_number'] == register_number), None)
                
                if student_data:
                    grade = student_data.get('grade', 0)

                    if grade == 0:
                        arrear.add(subject_id)
                    else:
                        if subject_id in arrear:
                            arrear.remove(subject_id)
                        completed.add(subject_id)

    db.students.update_one(
        {"register_number": register_number},
        {"$set": {"completed": list(completed), "arrear": list(arrear)}}
    )

print("Student completed and arrear arrays updated")

In [ ]:
def login():
    print("1: Log in as Student")
    print("2: Log in as Faculty")
    print("3: Log in as Admin")
    choice = input("Enter your choice: ")

    if choice == '1':
        username = input("Enter your register number: ")
        password = input("Enter your password: ")
        student = db.students.find_one({"register_number": username})
        if student.get("password") == password:
            student_dashboard(username)
        else:
            print("Invalid credentials.")
    elif choice == '2':
        username = input("Enter your faculty ID: ")
        password = input("Enter your password: ")
        faculty = db.faculty.find_one({"faculty_id": username})
        if faculty.get("password") == password:
            faculty_dashboard(username)
        else:
            print("Invalid credentials.")
    elif choice == '3':
        username = input("Enter admin username: ")
        password = input("Enter admin password: ")
        if username == 'admin' and password == 'password':
            admin_dashboard()
        else:
            print("Invalid credentials.")
    else:
        print("Invalid choice.")

In [ ]:
def admin_dashboard():
    while True:
        print("\nAdmin Dashboard")
        print("1: Manage Students Collection")
        print("2: Manage Faculty Collection")
        print("3: Manage Classes Collection")
        print("4: Manage Subjects Collection")
        print("5: Exit")
        choice = input("Enter your choice: ")

        if choice == '1':
            manage_students()
        elif choice == '2':
            manage_faculty()
        elif choice == '3':
            manage_classes()
        elif choice == '4':
            manage_subjects()
        elif choice == '5':
            break
        else:
            print("Invalid choice. Please try again.")

In [ ]:
def manage_students():
    sem_arr = ["F2122", "W2122", "F2223", "W2223", "F2324", "W2324"]

    print("\nManage Students Collection")
    print("1: View Student")
    print("2: Add Student")
    print("3: Delete Student")
    print("4: Update Student")
    choice = input("Enter your choice: ")

    if choice == '1':
        register_number = input("Enter register number: ")
        student = db['students'].find_one({"register_number": register_number})
        if student:
            print(student)
        else:
            print("Student not found.")
    elif choice == '2':
        name = input("Enter name: ")
        register_number = input("Enter register number: ")

        if register_number.startswith("21"):
            semesters = sem_arr
        elif register_number.startswith("22"):
            semesters = sem_arr[2:]
        elif register_number.startswith("23"):
            semesters = sem_arr[4:]
        else:
            semesters = []

        semester_data = []
        for sem in semesters:
            subject_list = input(f"Enter subjects for semester {sem} (comma separated): ").split(',')
            semester_data.append({"semester_name": sem, "subject_list": subject_list, "gpa": 0})

        student_data = {
            "name": name,
            "register_number": register_number,
            "semester_data": semester_data,
            "completed": [],
            "arrear": [],
            "cgpa": 0,
            "password": generate_password()
        }
        db['students'].insert_one(student_data)
        print("Student added.")
    elif choice == '3':
        register_number = input("Enter register number: ")
        db['students'].delete_one({"register_number": register_number})
        print("Student deleted.")
    elif choice == '4':
        register_number = input("Enter register number: ")
        field = input("Enter field to update: ")
        if field == 'semester_data':
            semester_name = input("Enter semester name: ")
            subfield = input("Enter field to update in semester_data (semester_name/subject_list): ")
            if subfield == 'semester_name':
                new_semester_name = input("Enter new semester name: ")
                db['students'].update_one(
                    {"register_number": register_number, "semester_data.semester_name": semester_name},
                    {"$set": {"semester_data.$.semester_name": new_semester_name}}
                )
            elif subfield == 'subject_list':
                subject_name = input("Enter subject name to update: ")
                new_subject_name = input("Enter new subject name: ")
                db['students'].update_one(
                    {"register_number": register_number, "semester_data.semester_name": semester_name, "semester_data.subject_list": subject_name},
                    {"$set": {"semester_data.$.subject_list.$": new_subject_name}}
                )
        else:
            new_value = input(f"Enter new value for {field}: ")
            db['students'].update_one({"register_number": register_number}, {"$set": {field: new_value}})
        print("Student updated.")
    else:
        print("Invalid choice.")

In [ ]:
def manage_faculty():
    print("\nManage Faculty Collection")
    print("1: View Faculty")
    print("2: Add Faculty")
    print("3: Delete Faculty")
    print("4: Update Faculty")
    choice = input("Enter your choice: ")

    if choice == '1':
        faculty_id = input("Enter faculty ID: ")
        faculty = db['faculty'].find_one({"faculty_id": faculty_id})
        if faculty:
            print(faculty)
        else:
            print("Faculty not found.")
    elif choice == '2':
        faculty_data = {
            "faculty_id": input("Enter faculty ID: "),
            "faculty_name": input("Enter faculty name: "),
            "class_data": [],
            "password": generate_password()
        }

        add_class_data = input("Do you want to add class data? (yes/no): ").strip().lower()
        while add_class_data == 'yes':
            semester_name = input("Enter semester name: ")
            class_list_input = input("Enter class list (comma-separated) or leave blank to skip: ")
            class_list = class_list_input.split(',') if class_list_input else []
            faculty_data['class_data'].append({
                "semester_name": semester_name,
                "class_list": class_list
            })
            add_class_data = input("Do you want to add more class data? (yes/no): ").strip().lower()

        db['faculty'].insert_one(faculty_data)
        print("Faculty added.")
    elif choice == '3':
        faculty_id = input("Enter faculty ID: ")
        db['faculty'].delete_one({"faculty_id": faculty_id})
        print("Faculty deleted.")
    elif choice == '4':
        faculty_id = input("Enter faculty ID: ")
        field = input("Enter field to update: ")
        if field == 'class_data':
            semester_name = input("Enter semester name: ")
            subfield = input("Enter field to update in class_data (semester_name/class_list): ")
            if subfield == 'semester_name':
                new_semester_name = input("Enter new semester name: ")
                db['faculty'].update_one(
                    {"faculty_id": faculty_id, "class_data.semester_name": semester_name},
                    {"$set": {"class_data.$[elem].semester_name": new_semester_name}},
                    array_filters=[{"elem.semester_name": semester_name}]
                )
            elif subfield == 'class_list':
                class_number = input("Enter class number to update: ")
                new_class_number = input("Enter new class number: ")
                db['faculty'].update_one(
                    {"faculty_id": faculty_id, "class_data.semester_name": semester_name},
                    {"$set": {"class_data.$[elem].class_list.$[cls]": new_class_number}},
                    array_filters=[{"elem.semester_name": semester_name}, {"cls": class_number}]
                )
        else:
            new_value = input(f"Enter new value for {field}: ")
            db['faculty'].update_one({"faculty_id": faculty_id}, {"$set": {field: new_value}})
        print("Faculty updated.")
    else:
        print("Invalid choice.")

In [ ]:
def manage_classes():
    print("\nManage Classes Collection")
    print("1: View Class")
    print("2: Add Class")
    print("3: Delete Class")
    print("4: Update Class")
    choice = input("Enter your choice: ")

    if choice == '1':
        class_number = input("Enter class number: ")
        class_doc = db['classes'].find_one({"class_number": class_number})
        if class_doc:
            print(class_doc)
        else:
            print("Class not found.")
    elif choice == '2':
        class_data = {
            "class_number": input("Enter class number: "),
            "subject_id": input("Enter subject ID: "),
            "faculty_id": input("Enter faculty ID: "),
            "student_data": []
        }
        subject = db['subjects'].find_one({"subject_id": subject_id})
        num_students = int(input("Enter number of students: "))
        for _ in range(num_students):
            reg_no = input("Enter student register number: ")
            if subject['type'] == 'relative':
                student_marks = {
                    "reg_no": reg_no,
                    "cat1": int(input("Enter CAT1 marks: ")),
                    "cat2": int(input("Enter CAT2 marks: ")),
                    "quiz1": int(input("Enter Quiz1 marks: ")),
                    "quiz2": int(input("Enter Quiz2 marks: ")),
                    "da": int(input("Enter DA marks: ")),
                    "fat": int(input("Enter FAT marks: "))
                }
            elif subject:
                student_marks = {
                    "reg_no": reg_no,
                    "ia1": int(input("Enter IA1 marks: ")),
                    "mt": int(input("Enter MT marks: ")),
                    "ia2": int(input("Enter IA2 marks: ")),
                    "fat": int(input("Enter FAT marks: "))
                }
            else:
                print(f"Subject with ID {subject_id} not found.")
                continue
            class_data['student_data'].append(student_marks)
        db['classes'].insert_one(class_data)
        print("Class added.")
    elif choice == '3':
        class_number = input("Enter class number: ")
        db['classes'].delete_one({"class_number": class_number})
        print("Class deleted.")
    elif choice == '4':
        class_number = input("Enter class number: ")
        field = input("Enter field to update: ")
        if field == 'student_data':
            reg_no = input("Enter student register number: ")
            subfield = input("Enter field to update in student_data (reg_no/marks): ")
            if subfield == 'reg_no':
                new_reg_no = input("Enter new register number: ")
                db['classes'].update_one(
                    {"class_number": class_number, "student_data.register_number": reg_no},
                    {"$set": {"student_data.$[elem].register_number": new_reg_no}},
                    array_filters=[{"elem.register_number": reg_no}]
                )
            elif subfield == 'marks':
                mark_field = input("Enter marks field to update: ")
                new_marks = int(input(f"Enter new value for {mark_field}: "))
                db['classes'].update_one(
                    {"class_number": class_number, "student_data.register_number": reg_no},
                    {"$set": {f"student_data.$[elem].{mark_field}": new_marks}},
                    array_filters=[{"elem.register_number": reg_no}]
                )
            else:
                print("Invalid subfield.")
        else:
            new_value = input(f"Enter new value for {field}: ")
            db['classes'].update_one({"class_number": class_number}, {"$set": {field: new_value}})
        print("Class updated.")
    else:
        print("Invalid choice.")

In [ ]:
def manage_subjects():
    print("\nManage Subjects Collection")
    print("1: View Subject")
    print("2: Add Subject")
    print("3: Delete Subject")
    print("4: Update Subject")
    choice = input("Enter your choice: ")

    if choice == '1':
        subject_id = input("Enter subject ID: ")
        subject = db['subjects'].find_one({"subject_id": subject_id})
        if subject:
            print(subject)
        else:
            print("Subject not found.")
    elif choice == '2':
        subject_data = {
            "subject_id": input("Enter subject ID: "),
            "subject_name": input("Enter subject name: "),
            "type": input("Enter subject type (absolute/relative): "),
            "credits": input("Enter number of credits: ")
        }
        db['subjects'].insert_one(subject_data)
        print("Subject added.")
    elif choice == '3':
        subject_id = input("Enter subject ID: ")
        db['subjects'].delete_one({"subject_id": subject_id})
        print("Subject deleted.")
    elif choice == '4':
        subject_id = input("Enter subject ID: ")
        field = input("Enter field to update: ")
        new_value = input(f"Enter new value for {field}: ")
        db['subjects'].update_one({"subject_id": subject_id}, {"$set": {field: new_value}})
        print("Subject updated.")
    else:
        print("Invalid choice.")

In [ ]:
def faculty_dashboard(faculty_id):
    while True:
        print("\nFaculty Dashboard")
        print("1: Generate Timetable")
        print("2: Manage Your Classes")
        print("3: Exit")
        choice = input("Enter your choice: ")

        if choice == '1':
            timetable = generate_faculty_timetable(faculty_id)
            for semester, sem_timetable in timetable.items():
                print(f"\nTimetable for Semester: {semester}")
                for day, slots in sem_timetable.items():
                    print(f"{day}:")
                    for slot, class_number in slots.items():
                        print(f"  {slot}: {class_number}")
        elif choice == '2':
            view_update_class_data(faculty_id)
        elif choice == '3':
            break
        else:
            print("Invalid choice. Please try again.")

In [ ]:
# Time slots for the timetable
time_slots = [
    "08:00-09:00", "09:00-10:00", "10:00-11:00", "11:00-12:00", "12:00-13:00"
]

weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

def generate_semester_timetable(semester_prefix):
    query = {"class_number": {"$regex": f"^{semester_prefix}"}}
    classes = list(classes_collection.find(query))
    
    timetable = {day: {slot: None for slot in time_slots} for day in weekdays}
    class_index = 0
    
    for class_doc in classes:
        allocated = False
        for day in weekdays:
            if allocated:
                break
            for slot in time_slots:
                if timetable[day][slot] is None:
                    timetable[day][slot] = class_doc["class_number"]
                    allocated = True
                    break

    return timetable

def generate_all_semester_timetables():
    sem_arr = ['F2122', 'W2122', 'F2223', 'W2223', 'F2324', 'W2324']
    all_timetables = {}
    
    for sem in sem_arr:
        timetable = generate_semester_timetable(sem)
        all_timetables[sem] = timetable
    
    return all_timetables

In [ ]:
def generate_faculty_timetable(faculty_id):
    faculty = faculty_collection.find_one({"faculty_id": faculty_id})
    
    if not faculty:
        print("Faculty not found")
        return
    
    all_semester_timetables = generate_all_semester_timetables()
    faculty_timetable = {}

    for semester_data in faculty["class_data"]:
        semester_name = semester_data["semester_name"]
        class_list = semester_data["class_list"]
        faculty_timetable[semester_name] = {day: {slot: None for slot in time_slots} for day in weekdays}

        semester_timetable = all_semester_timetables.get(semester_name)
        
        if semester_timetable:
            for day, slots in semester_timetable.items():
                for slot, class_number in slots.items():
                    if class_number in class_list:
                        faculty_timetable[semester_name][day][slot] = class_number

    return faculty_timetable

In [ ]:
def view_update_class_data(faculty_id):
    faculty = faculty_collection.find_one({"faculty_id": faculty_id})
    
    if not faculty:
        print("Faculty not found")
        return
    
    print("Select Semester:")
    for i, semester_data in enumerate(faculty["class_data"], 1):
        print(f"{i}: {semester_data['semester_name']}")
    
    semester_choice = int(input("Enter your choice: ")) - 1
    selected_semester = faculty["class_data"][semester_choice]["semester_name"]
    class_list = faculty["class_data"][semester_choice]["class_list"]

    print(f"\nClasses in Semester {selected_semester}:")
    for class_number in class_list:
        print(class_number)
    
    class_number = input("Enter class number to update: ")
    if class_number not in class_list:
        print("Invalid class number. You can only update your assigned classes.")
        return

    reg_no = input("Enter student register number: ")
    subfield = input("Enter marks field to update: ")
    new_marks = int(input(f"Enter new value for {subfield}: "))
    db['classes'].update_one(
        {"class_number": class_number, "student_data.register_number": reg_no},
        {"$set": {f"student_data.$[elem].{subfield}": new_marks}},
        array_filters=[{"elem.register_number": reg_no}]
    )
    print(f"Updated {subfield} for register number {reg_no} in class {class_number}.")

In [ ]:
def student_dashboard(register_number):
    while True:
        print("Student Dashboard")
        print("1: Generate Timetable")
        print("2: View Your Classes")
        print("3: Exit")
        choice = input("Enter your choice: ")

        if choice == '1':
            generate_student_timetable(register_number)
        elif choice == '2':
            view_student_data(register_number)
        elif choice == '3':
            break
        else:
            print("Invalid choice. Please try again.")

In [ ]:
def generate_student_timetable(register_number):
    student = students_collection.find_one({"register_number": register_number})
    
    if not student:
        print(f"Student with register number {register_number} not found.")
        return
    
    all_semester_timetables = generate_all_semester_timetables()
    for semester_data in student["semester_data"]:
        semester_name = semester_data["semester_name"]
        subject_list = semester_data["subject_list"]
        
        print(f"Semester: {semester_name}")
        
        if not subject_list:
            print("No subjects registered for this semester.")
            continue
        
        student_timetable = {day: {slot: None for slot in time_slots} for day in weekdays}
        
        for subject_id in subject_list:
            query = {
                "class_number": {"$regex": f"^{semester_name}"},
                "subject_id": subject_id,
                "student_data.register_number": register_number
            }
            classes = list(classes_collection.find(query))
            
            for class_doc in classes:
                class_number = class_doc["class_number"]
                allocated_time = False
                
                for day in weekdays:
                    if allocated_time:
                        break
                    for slot in time_slots:
                        if not student_timetable[day][slot] and all_semester_timetables[semester_name][day][slot] == class_number:
                            student_timetable[day][slot] = class_number
                            allocated_time = True
                            break
        
        for day in weekdays:
            print(f"Day: {day}")
            if all(value is None for value in student_timetable[day].values()):
                print("--------------------")
            else:
                for slot, class_number in student_timetable[day].items():
                    if class_number:
                        print(f"   Time: {slot} - Class Number: {class_number}")
                print("--------------------")

In [ ]:
def view_student_data(register_number):
    
    student = db.students.find_one({"register_number": register_number})
    
    if student:
        print("Student Information:")
        print(f"Name: {student['name']}")
        print(f"Register Number: {student['register_number']}")
        print("Semester Data:")
        for semester in student.get('semester_data', []):
            print(f"  Semester: {semester['semester_name']}")
            print(f"  Subjects: {', '.join(semester['subject_list'])}")
            print(f"  GPA: {semester['gpa']}")
        print(f"Completed: {', '.join(student.get('completed', []))}")
        print(f"Arrear: {', '.join(student.get('arrear', []))}")
        print(f"CGPA: {student.get('cgpa', 'N/A')}")
        
        view_marks = input("Do you want to view your mark data? (yes/no): ").strip().lower()
        
        if view_marks == 'yes':
            print("Mark Data:")
            for semester in student.get('semester_data', []):
                for subject_id in semester.get('subject_list', []):
                    class_document = db.classes.find_one({
                        "subject_id": subject_id,
                        "student_data.register_number": register_number
                    })
                    
                    if class_document:
                        student_data = next((data for data in class_document['student_data'] if data['register_number'] == register_number), None)
                        
                        if student_data:
                            subject_info = db.subjects.find_one({"subject_id": subject_id})
                            
                            if subject_info:
                                if subject_info['type'] == 'absolute':
                                    ia1 = student_data.get('ia1', '-')
                                    mt = student_data.get('mt', '-')
                                    ia2 = student_data.get('ia2', '-')
                                    fat = student_data.get('fat', '-')
                                    
                                    print(f"  Class: {class_document['class_number']}")
                                    print(f"  Subject: {class_document['subject_id']}")
                                    print(f"    IA1: {ia1}")
                                    print(f"    MT: {mt}")
                                    print(f"    IA2: {ia2}")
                                    print(f"    FAT: {fat}")
                                elif subject_info['type'] == 'relative':
                                    cat1 = student_data.get('cat1', '-')
                                    cat2 = student_data.get('cat2', '-')
                                    quiz1 = student_data.get('quiz1', '-')
                                    quiz2 = student_data.get('quiz2', '-')
                                    da = student_data.get('da', '-')
                                    fat = student_data.get('fat', '-')
                                    
                                    print(f"  Class: {class_document['class_number']}")
                                    print(f"  Subject: {class_document['subject_id']}")
                                    print(f"    CAT1: {cat1}")
                                    print(f"    CAT2: {cat2}")
                                    print(f"    Quiz1: {quiz1}")
                                    print(f"    Quiz2: {quiz2}")
                                    print(f"    DA: {da}")
                                    print(f"    FAT: {fat}")
                                    
                            else:
                                print(f"Subject information not found for {subject_id}")
                    else:
                        print(f"Class not found for subject {subject_id}")
    else:
        print("Student not found.")

In [ ]:
if __name__ == "__main__":
    login()